name: mydotnet project

on:
  push:
    branches:
      - develop

jobs:
  dotnet_publish:
    runs-on: self-hosted

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: this is my dotnet publish command
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o /demo