name: mydotnet project

on:
  push:
    branches:
      - develop

jobs:
  dotnet_publish:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@v5
        with:
          mysonar: ${{ secrets.SONAR_TOKEN }}
          mysonar_url: ${{ secrets.SONAR_URL }}

      - name: install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.100"

      - name: dotnet publish
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o demo
